packages:
  - apps/*
  - packages/*

allowBuilds:
  '@clerk/shared': false
  '@sentry/cli': false
  core-js: false
  esbuild: true
  sharp: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1125.0'
