/**
 * Offline content generation. Run locally, never from a request.
 *
 *   node --env-file=.env.local scripts/generate-content.ts generate --count 5
 *   node --env-file=.env.local scripts/generate-content.ts sql
 *
 * `generate` writes one reviewable JSON file per passage into content/passages/.
 * `sql` turns whatever JSON is in that directory into content/seed.sql.
 *
 * The split is deliberate: passages get read and corrected by a human between
 * the two steps, and edits go into the JSON, not into generated SQL.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { generatePassage } from '@bandzen/ai/generate';
import { type GeneratedPassage as Passage } from '@bandzen/ai/schemas';

const SEED_DIR = join(import.meta.dirname, '..', 'content', 'passages');
const PROMPTS_FILE = join(import.meta.dirname, '..', 'content', 'prompts.json');
const SQL_OUT = join(import.meta.dirname, '..', 'content', 'seed.sql');

type WritingChartData = {
  kind: 'line' | 'bar';
  title: string;
  unit?: string;
  xLabel?: string;
  series: { name: string; points: [number | string, number][] }[];
};

type Prompt = {
  slug: string;
  task: 1 | 2;
  format?: 'academic' | 'general';
  promptText: string;
  chartData?: WritingChartData;
};

async function generate(count: number) {
  mkdirSync(SEED_DIR, { recursive: true });

  const existing = new Set(
    readdirSync(SEED_DIR)
      .filter((f) => f.endsWith('.json'))
      .map((f) => f.replace(/\.json$/, '')),
  );

  for (let i = 0; i < count; i += 1) {
    const { data: passage, warnings } = await generatePassage({
      avoid: [...existing],
    });
    if (warnings.length) {
      console.warn(`  ⚠ ${passage.slug}: ${warnings.join('; ')}`);
    }

    writeFileSync(
      join(SEED_DIR, `${passage.slug}.json`),
      `${JSON.stringify(passage, null, 2)}\n`,
    );
    existing.add(passage.slug);
    console.log(`  ✓ ${passage.slug} — ${passage.title}`);
  }

  console.log(
    `\nReview the JSON in content/passages/, then: node scripts/generate-content.mts sql`,
  );
}

const quote = (v: string) => `'${v.replaceAll("'", "''")}'`;
const jsonb = (v: unknown) => `${quote(JSON.stringify(v))}::jsonb`;

function toSql() {
  const files = readdirSync(SEED_DIR).filter((f) => f.endsWith('.json'));
  if (!files.length)
    throw new Error(`No JSON in ${SEED_DIR} — run \`generate\` first.`);

  const out: string[] = [
    '-- Generated by scripts/generate-content.ts. Edit the JSON in content/passages/,',
    '-- then regenerate; do not hand-edit this file.',
    '',
    'begin;',
    '',
  ];

  for (const file of files.sort()) {
    const p = JSON.parse(readFileSync(join(SEED_DIR, file), 'utf8')) as Passage;

    out.push(
      `-- ${p.title}`,
      `insert into public.passages (slug, title, body, topic, headings, difficulty)`,
      `values (${quote(p.slug)}, ${quote(p.title)}, ${quote(p.body)}, ${quote(p.topic)}, ${p.headings?.length ? jsonb(p.headings) : 'null'}, ${p.difficulty})`,
      `on conflict (slug) do update set`,
      `  title = excluded.title, body = excluded.body, topic = excluded.topic,`,
      `  headings = excluded.headings, difficulty = excluded.difficulty;`,
      '',
    );

    for (const q of p.questions) {
      out.push(
        `with p as (select id from public.passages where slug = ${quote(p.slug)}),`,
        `     q as (`,
        `       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)`,
        `       select p.id, ${q.idx}, ${quote(q.kind)}::public.question_kind, ${quote(q.prompt)},`,
        `              ${q.options ? jsonb(q.options) : 'null'}, ${quote(q.evidence)}, ${quote(q.explanation)}`,
        `       from p`,
        `       on conflict (passage_id, idx) do update set`,
        `         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,`,
        `         evidence = excluded.evidence, explanation = excluded.explanation`,
        `       returning id`,
        `     )`,
        `insert into public.question_answers (question_id, answer)`,
        `select q.id, ${jsonb(q.answer)} from q`,
        `on conflict (question_id) do update set answer = excluded.answer;`,
        '',
      );
    }
  }

  // Writing prompts are hand-authored in content/prompts.json rather than
  // generated: there are only a few dozen, they barely change, and the task
  // rubric matters more than volume.
  let promptCount = 0;
  if (existsSync(PROMPTS_FILE)) {
    const prompts = JSON.parse(readFileSync(PROMPTS_FILE, 'utf8')) as Prompt[];
    promptCount = prompts.length;
    for (const prompt of prompts) {
      out.push(
        `insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)`,
        `values (${quote(prompt.slug)}, ${prompt.task}, ${quote(prompt.format ?? 'academic')}::public.test_format, ${quote(prompt.promptText)}, ${prompt.chartData ? jsonb(prompt.chartData) : 'null'})`,
        `on conflict (slug) do update set`,
        `  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,`,
        `  chart_data = excluded.chart_data;`,
        '',
      );
    }
  }

  out.push('commit;', '');
  writeFileSync(SQL_OUT, out.join('\n'));
  console.log(
    `Wrote ${SQL_OUT} from ${files.length} passage(s) and ${promptCount} prompt(s).`,
  );
}

const [command, ...rest] = process.argv.slice(2);

if (command === 'generate') {
  const flag = rest.indexOf('--count');
  const count = flag === -1 ? 1 : Number(rest[flag + 1]);
  if (!Number.isInteger(count) || count < 1)
    throw new Error('--count must be a positive integer');
  await generate(count);
} else if (command === 'sql') {
  toSql();
} else {
  console.log(`usage:
  generate --count <n>   write <n> reviewable passage JSON files
  sql                    build content/seed.sql from those files`);
  process.exit(1);
}
