/**
 * Offline listening-content generation. Run locally, never from a request.
 *
 *   node --env-file=.env.local scripts/generate-listening-content.mts generate --count 5
 *   node --env-file=.env.local scripts/generate-listening-content.mts sql
 *
 * `generate` writes one reviewable JSON file per track into content/listening/,
 * with no audio yet. `sql` turns whatever JSON is in that directory into
 * content/listening-seed.sql — a separate file from content/seed.sql, applied
 * with `node scripts/seed.mts content/listening-seed.sql`, so this script and
 * generate-content.mts can never race each other overwriting the same file.
 *
 * The split from `generate` to `sql` is deliberate, same as passages: a human
 * reads and corrects the transcript and questions between the two steps, and
 * `scripts/synthesize-listening-audio.mts` turns the reviewed transcript into
 * an audioUrl in between — before anything is spent on TTS.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { generateListeningTrack } from '@bandzen/ai/generate';
import { type GeneratedListeningTrack as Track } from '@bandzen/ai/schemas';

const SEED_DIR = join(import.meta.dirname, '..', 'content', 'listening');
const SQL_OUT = join(
  import.meta.dirname,
  '..',
  'content',
  'listening-seed.sql',
);

async function generate(count: number) {
  mkdirSync(SEED_DIR, { recursive: true });

  const existing = new Set(
    readdirSync(SEED_DIR)
      .filter((f) => f.endsWith('.json'))
      .map((f) => f.replace(/\.json$/, '')),
  );

  for (let i = 0; i < count; i += 1) {
    const { data: track, warnings } = await generateListeningTrack({
      avoid: [...existing],
    });
    if (warnings.length) {
      console.warn(`  ⚠ ${track.slug}: ${warnings.join('; ')}`);
    }

    writeFileSync(
      join(SEED_DIR, `${track.slug}.json`),
      `${JSON.stringify(track, null, 2)}\n`,
    );
    existing.add(track.slug);
    console.log(`  ✓ ${track.slug} — ${track.title}`);
  }

  console.log(
    `\nReview the JSON in content/listening/, then: node scripts/synthesize-listening-audio.mts`,
  );
}

const quote = (v: string) => `'${v.replaceAll("'", "''")}'`;
const jsonb = (v: unknown) => `${quote(JSON.stringify(v))}::jsonb`;

function toSql() {
  const files = readdirSync(SEED_DIR).filter((f) => f.endsWith('.json'));
  if (!files.length)
    throw new Error(`No JSON in ${SEED_DIR} — run \`generate\` first.`);

  const out: string[] = [
    '-- Generated by scripts/generate-listening-content.ts. Edit the JSON in',
    '-- content/listening/, then regenerate; do not hand-edit this file.',
    '',
    'begin;',
    '',
  ];

  let missingAudio = 0;

  for (const file of files.sort()) {
    const t = JSON.parse(
      readFileSync(join(SEED_DIR, file), 'utf8'),
    ) as Track & {
      audioUrl?: string;
      peaks?: number[];
      durationSeconds?: number;
    };
    if (!t.audioUrl) {
      missingAudio += 1;
      console.warn(
        `  ⚠ ${t.slug} has no audioUrl yet — run scripts/synthesize-listening-audio.mts first`,
      );
      continue;
    }

    out.push(
      `-- ${t.title}`,
      `insert into public.listening_tracks (slug, title, topic, transcript, audio_url, matching_options, peaks, duration_seconds, difficulty)`,
      `values (${quote(t.slug)}, ${quote(t.title)}, ${quote(t.topic)}, ${quote(t.transcript)}, ${quote(t.audioUrl)}, ${t.matchingOptions?.length ? jsonb(t.matchingOptions) : 'null'}, ${t.peaks?.length ? jsonb(t.peaks) : 'null'}, ${t.durationSeconds ?? 'null'}, ${t.difficulty})`,
      `on conflict (slug) do update set`,
      `  title = excluded.title, topic = excluded.topic, transcript = excluded.transcript,`,
      `  audio_url = excluded.audio_url, matching_options = excluded.matching_options,`,
      `  peaks = excluded.peaks, duration_seconds = excluded.duration_seconds, difficulty = excluded.difficulty;`,
      '',
    );

    for (const q of t.questions) {
      out.push(
        `with tr as (select id from public.listening_tracks where slug = ${quote(t.slug)}),`,
        `     q as (`,
        `       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)`,
        `       select tr.id, ${q.idx}, ${quote(q.kind)}::public.question_kind, ${quote(q.prompt)},`,
        `              ${q.options ? jsonb(q.options) : 'null'}, ${quote(q.evidence)}, ${quote(q.explanation)}`,
        `       from tr`,
        `       on conflict (track_id, idx) do update set`,
        `         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,`,
        `         evidence = excluded.evidence, explanation = excluded.explanation`,
        `       returning id`,
        `     )`,
        `insert into public.question_answers (question_id, answer)`,
        `select q.id, ${jsonb(q.answer)} from q`,
        `on conflict (question_id) do update set answer = excluded.answer;`,
        '',
      );
    }
  }

  out.push('commit;', '');
  writeFileSync(SQL_OUT, out.join('\n'));
  const seeded = files.length - missingAudio;
  console.log(`Wrote ${SQL_OUT} from ${seeded} track(s).`);
  if (missingAudio) {
    console.log(
      `${missingAudio} track(s) skipped for missing audio — see warnings above.`,
    );
  }
}

const [command, ...rest] = process.argv.slice(2);

if (command === 'generate') {
  const flag = rest.indexOf('--count');
  const count = flag === -1 ? 1 : Number(rest[flag + 1]);
  if (!Number.isInteger(count) || count < 1)
    throw new Error('--count must be a positive integer');
  await generate(count);
} else if (command === 'sql') {
  toSql();
} else {
  console.log(`usage:
  generate --count <n>   write <n> reviewable track JSON files
  sql                    build content/listening-seed.sql from those files`);
  process.exit(1);
}
