/**
 * Offline speaking-content generation. Run locally, never from a request.
 *
 *   node --env-file=.env.local scripts/generate-speaking-content.mts generate --count 5
 *   node --env-file=.env.local scripts/generate-speaking-content.mts sql
 *
 * `generate` writes one reviewable JSON file per test into content/speaking/,
 * with the three parts flattened to an ordered `prompts` array and no examiner
 * audio yet. A human reviews it, then `scripts/synthesize-speaking-audio.mts`
 * fills in each prompt's `audioUrl`, then `sql` builds
 * content/speaking-seed.sql (applied with `node scripts/seed.mts
 * content/speaking-seed.sql`). Same split as the listening pipeline.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import {
  generateSpeakingTest,
  type SpeakingTestFile as TestFile,
} from '@bandzen/ai/generate';

const SEED_DIR = join(import.meta.dirname, '..', 'content', 'speaking');
const SQL_OUT = join(import.meta.dirname, '..', 'content', 'speaking-seed.sql');

async function generate(count: number) {
  mkdirSync(SEED_DIR, { recursive: true });

  const existing = new Set(
    readdirSync(SEED_DIR)
      .filter((f) => f.endsWith('.json'))
      .map((f) => f.replace(/\.json$/, '')),
  );

  for (let i = 0; i < count; i += 1) {
    const { data: test, warnings } = await generateSpeakingTest({
      avoid: [...existing],
    });
    if (warnings.length)
      console.warn(`  ⚠ ${test.slug}: ${warnings.join('; ')}`);

    writeFileSync(
      join(SEED_DIR, `${test.slug}.json`),
      `${JSON.stringify(test, null, 2)}\n`,
    );
    existing.add(test.slug);
    console.log(`  ✓ ${test.slug} — ${test.title}`);
  }

  console.log(
    `\nReview the JSON in content/speaking/, then: node scripts/synthesize-speaking-audio.mts`,
  );
}

const quote = (v: string) => `'${v.replaceAll("'", "''")}'`;
const jsonb = (v: unknown) => `${quote(JSON.stringify(v))}::jsonb`;

function toSql() {
  const files = readdirSync(SEED_DIR).filter((f) => f.endsWith('.json'));
  if (!files.length)
    throw new Error(`No JSON in ${SEED_DIR} — run \`generate\` first.`);

  const out: string[] = [
    '-- Generated by scripts/generate-speaking-content.mts. Edit the JSON in',
    '-- content/speaking/, then regenerate; do not hand-edit this file.',
    '',
    'begin;',
    '',
  ];

  let missingAudio = 0;

  for (const file of files.sort()) {
    const t = JSON.parse(
      readFileSync(join(SEED_DIR, file), 'utf8'),
    ) as TestFile;

    if (t.prompts.some((p) => !p.audioUrl)) {
      missingAudio += 1;
      console.warn(
        `  ⚠ ${t.slug} has prompts without audioUrl — run scripts/synthesize-speaking-audio.mts first`,
      );
      continue;
    }

    out.push(
      `-- ${t.title}`,
      `insert into public.speaking_tests (slug, title, topic, difficulty)`,
      `values (${quote(t.slug)}, ${quote(t.title)}, ${quote(t.topic)}, ${t.difficulty})`,
      `on conflict (slug) do update set`,
      `  title = excluded.title, topic = excluded.topic, difficulty = excluded.difficulty;`,
      '',
    );

    for (const p of t.prompts) {
      out.push(
        `insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)`,
        `select st.id, ${p.idx}, ${p.part}, ${quote(p.text)},`,
        `       ${p.cueCardPoints?.length ? jsonb(p.cueCardPoints) : 'null'}, ${p.prepSeconds}, ${quote(p.audioUrl!)}`,
        `from public.speaking_tests st where st.slug = ${quote(t.slug)}`,
        `on conflict (test_id, idx) do update set`,
        `  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,`,
        `  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;`,
        '',
      );
    }
  }

  out.push('commit;', '');
  writeFileSync(SQL_OUT, out.join('\n'));
  console.log(`Wrote ${SQL_OUT} from ${files.length - missingAudio} test(s).`);
  if (missingAudio) {
    console.log(`${missingAudio} test(s) skipped for missing audio.`);
  }
}

const [command, ...rest] = process.argv.slice(2);

if (command === 'generate') {
  const flag = rest.indexOf('--count');
  const count = flag === -1 ? 1 : Number(rest[flag + 1]);
  if (!Number.isInteger(count) || count < 1)
    throw new Error('--count must be a positive integer');
  await generate(count);
} else if (command === 'sql') {
  toSql();
} else {
  console.log(`usage:
  generate --count <n>   write <n> reviewable test JSON files
  sql                    build content/speaking-seed.sql from those files`);
  process.exit(1);
}
