-- Generated by scripts/generate-listening-content.ts. Edit the JSON in
-- content/listening/, then regenerate; do not hand-edit this file.

begin;

-- Orientation at a Community Tool Library
insert into public.listening_tracks (slug, title, topic, transcript, audio_url, matching_options, difficulty)
values ('community-tool-library-orientation', 'Orientation at a Community Tool Library', 'A new member asks about borrowing tools and using shared work areas', 'Maya: Good evening, everyone. Tonight''s short orientation is to explain how borrowing equipment works at the Riverside Tool Library.

Leo: Thanks, Maya. I joined online, but I haven''t visited before. Is this the main building?

Maya: Yes, though people often walk past it. The front entrance is on Mill Lane, between the chemist and the bicycle shop.

Leo: Right, I''ll remember that. What kind of membership do most people choose?

Maya: The standard annual membership is twelve pounds, and that suits most households. The student annual membership is seven pounds, but it requires a current college card. We also sell a day pass, but that is really for visitors who need just one tool.

Leo: And is there a deposit when we borrow something expensive?

Maya: For power tools, we take a refundable deposit of twenty pounds. You get it back when the tool returns in good condition.

Leo: How long can I keep things at home?

Maya: Most items go out for one week. If you bring something back late, the fee is one pound per day, because other members may be waiting.

Leo: I saw different rooms on the map. Are there separate rules for each area?

Maya: There are. For the repair bench, the key point is: Ask staff for a safety check before you switch anything on.

Leo: That makes sense, especially with drills and saws.

Maya: For the sewing corner, the key point is: Bring your own consumables, such as thread, buttons and fabric scraps.

Leo: So the machines are shared, but not the materials.

Maya: Exactly. For the paint station, the key point is: Clean it immediately after use, even if the next person says they do not mind.

Leo: What about the garden tools? I noticed they were by the back door.

Maya: Those can be borrowed like any other item, but muddy tools must be rinsed outside. Please do not use the toilet sinks for that.

Leo: Are there training sessions for beginners?

Maya: Yes. The workshop next Tuesday is called Bike Brakes for Beginners. It starts at six thirty and lasts about ninety minutes.

Leo: Great. Last question: what happens if I open a box at home and a piece is missing?

Maya: If anything is missing, don''t try to replace it yourself; email a photo to the loans desk.

Leo: Got it. This seems much easier than buying tools I might only use once.

Maya: That''s the idea. Borrow carefully, return on time, and tell us quickly if something is damaged or incomplete.', 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/listening/community-tool-library-orientation.mp3', '["Ask staff for a safety check","Bring your own consumables","Clean it immediately after use","Return it by noon","Use it only outdoors","Label it with your name","Book it two weeks in advance"]'::jsonb, 2)
on conflict (slug) do update set
  title = excluded.title, topic = excluded.topic, transcript = excluded.transcript,
  audio_url = excluded.audio_url, matching_options = excluded.matching_options,
  difficulty = excluded.difficulty;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 1, 'multiple_choice'::public.question_kind, 'What is the main purpose of the orientation?',
              '["to explain how borrowing equipment works","to advertise a new bicycle shop","to train staff in customer service","to collect suggestions for new tools"]'::jsonb, 'Maya: Good evening, everyone. Tonight''s short orientation is to explain how borrowing equipment works at the Riverside Tool Library.', 'Maya states that the orientation is to explain the borrowing system.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["to explain how borrowing equipment works"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 2, 'sentence_completion'::public.question_kind, 'Complete the sentence. Write NO MORE THAN TWO WORDS. The front entrance is on ________.',
              null, 'Maya: Yes, though people often walk past it. The front entrance is on Mill Lane, between the chemist and the bicycle shop.', 'Maya gives the location of the front entrance as Mill Lane.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Mill Lane"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 3, 'multiple_choice'::public.question_kind, 'Which membership does Maya say suits most households?',
              '["the standard annual membership","the student annual membership","the day pass","the visitor card"]'::jsonb, 'Maya: The standard annual membership is twelve pounds, and that suits most households. The student annual membership is seven pounds, but it requires a current college card. We also sell a day pass, but that is really for visitors who need just one tool.', 'Maya directly says the standard annual membership suits most households.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["the standard annual membership"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 4, 'sentence_completion'::public.question_kind, 'Complete the sentence. Write NO MORE THAN TWO WORDS. For power tools, members pay a refundable deposit of ________.',
              null, 'Maya: For power tools, we take a refundable deposit of twenty pounds. You get it back when the tool returns in good condition.', 'The deposit amount mentioned for power tools is twenty pounds.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["twenty pounds"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 5, 'multiple_choice'::public.question_kind, 'What is the late return fee?',
              '["one pound per day","two pounds per week","seven pounds per item","twelve pounds per month"]'::jsonb, 'Maya: Most items go out for one week. If you bring something back late, the fee is one pound per day, because other members may be waiting.', 'Maya says the fee for a late return is one pound per day.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["one pound per day"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 6, 'matching'::public.question_kind, 'Which instruction is given for the repair bench? Choose from the matching options.',
              null, 'Maya: There are. For the repair bench, the key point is: Ask staff for a safety check before you switch anything on.', 'The repair bench instruction is to ask staff for a safety check.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Ask staff for a safety check"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 7, 'matching'::public.question_kind, 'Which instruction is given for the sewing corner? Choose from the matching options.',
              null, 'Maya: For the sewing corner, the key point is: Bring your own consumables, such as thread, buttons and fabric scraps.', 'For the sewing corner, members must bring their own consumables.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Bring your own consumables"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 8, 'matching'::public.question_kind, 'Which instruction is given for the paint station? Choose from the matching options.',
              null, 'Maya: Exactly. For the paint station, the key point is: Clean it immediately after use, even if the next person says they do not mind.', 'The paint station must be cleaned immediately after use.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Clean it immediately after use"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 9, 'sentence_completion'::public.question_kind, 'Complete the sentence. Write NO MORE THAN FOUR WORDS. The workshop next Tuesday is called ________.',
              null, 'Maya: Yes. The workshop next Tuesday is called Bike Brakes for Beginners. It starts at six thirty and lasts about ninety minutes.', 'Maya gives the exact title of the workshop.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Bike Brakes for Beginners"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with tr as (select id from public.listening_tracks where slug = 'community-tool-library-orientation'),
     q as (
       insert into public.questions (track_id, idx, kind, prompt, options, evidence, explanation)
       select tr.id, 10, 'multiple_choice'::public.question_kind, 'What should Leo do if a piece is missing from a box?',
              '["email a photo to the loans desk","buy a replacement immediately","return the box without comment","ask the next borrower to check"]'::jsonb, 'Maya: If anything is missing, don''t try to replace it yourself; email a photo to the loans desk.', 'Maya tells Leo not to replace the missing part himself, but to email a photo to the loans desk.'
       from tr
       on conflict (track_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["email a photo to the loans desk"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

commit;
