-- Generated by scripts/generate-content.ts. Edit the JSON in content/passages/,
-- then regenerate; do not hand-edit this file.

begin;

-- Fungi Beneath City Trees
insert into public.passages (slug, title, body, topic, headings, difficulty)
values ('fungi-beneath-city-trees', 'Fungi Beneath City Trees', 'A
Urban trees are often presented as simple objects of beautification, yet many cities now treat them as a form of living infrastructure. Their crowns intercept rain, moderate heat and filter pollutants, while their roots help hold soil in place during storms. The services provided by mature street trees influence municipal budgets indirectly, because cooler pavements last longer, shaded buildings require less energy, and healthier neighbourhoods can reduce public health costs. However, the survival of urban trees depends on processes that occur largely out of sight. Among the most important of these processes are the relationships between roots and fungi, which can determine how well a tree obtains nutrients and tolerates stress.

B
Mycorrhizae are partnerships in which fungi receive sugars made by photosynthesis and, in return, improve the plant’s access to water and mineral nutrients. Two broad types are especially relevant to urban forestry. In ectomycorrhizal associations, fungal tissue forms a sheath around young roots and extends as threads into the surrounding soil. These fungi are common on oaks, pines and beeches, and some produce familiar mushrooms. Arbuscular mycorrhizal fungi enter root cells and are common in maples, planes and many tropical street trees; they do not produce conspicuous mushrooms at the soil surface. Although the exchange seems straightforward, it is regulated by chemical signals and by the relative scarcity of nutrients. When phosphorus or nitrogen is difficult for roots to reach, the fungal partner may become particularly valuable.

C
Urban conditions can weaken these alliances. In paved streets, tree roots often occupy narrow pits surrounded by compacted subsoil, concrete and buried pipes. Compaction reduces pore spaces, making it harder for fungal filaments to spread and for oxygen to reach roots. De-icing salts, heavy metals from traffic and repeated excavation for utilities can also alter the soil community. Heat adds another pressure: soil under dark asphalt may remain warmer at night than soil in a park, changing the balance among fungal species. The result is not simply fewer fungi, but a community that may be less suited to supporting long-lived trees.

D
Until recently, the underground nature of mycorrhizae made them difficult to study in streets and plazas. Researchers relied on root samples and microscopic inspection, methods that were slow and could miss species that were not actively colonising roots at the moment of sampling. Newer studies combine DNA sequencing with measurements of soil chemistry, allowing scientists to identify fungi from tiny fragments in the soil. Some experiments use stable isotope labels to trace whether carbon moves from a tree into fungal tissue or whether nutrients move in the opposite direction. A survey published in 2021 of street trees in Melbourne found that fungal species richness was lowest where soil had high bulk density and low organic matter. Such findings do not reveal every exchange, but they help explain why two trees of the same species can perform very differently on neighbouring streets.

E
The most persuasive recommendations are not to add fungi indiscriminately, but to improve the habitat in which useful fungi already live. In nurseries, seedlings can be grown in soils that encourage appropriate mycorrhizal partners before the trees are planted. After planting, structural soils and suspended pavements can provide larger rooting volumes without sacrificing pedestrian surfaces. Municipal crews can also protect existing networks by leaving leaf litter under tree crowns, limiting fungicide use and designing continuous soil trenches beneath pavements. Commercial inoculants are sometimes helpful, especially where soil has been imported or sterilised, but their effects are inconsistent. An introduced strain may fail to establish or may compete with fungi already adapted to the site. For this reason, many urban ecologists argue that fungal management should begin with reducing disturbance and increasing organic matter.

F
Mycorrhizal research has nevertheless encouraged a broader view of what counts as tree care. Watering and pruning are visible tasks, whereas maintaining soil biology is less obvious and harder to specify in contracts. The economic returns of mycorrhizal management are difficult to calculate, in part because fungal contributions are indirect and interact with irrigation, pruning and the genetics of the tree. There are also equity issues: wealthier districts usually have older trees, larger planting beds and more frequent maintenance, all of which favour healthier soil communities. If cities want the benefits of mature canopies to be distributed fairly, they may need to invest not only in planting new trees but also in the hidden fungal networks that help those trees persist.', 'Urban ecology and mycorrhizal fungi', '["The basic forms of a root-fungus partnership","Urban stresses that damage underground alliances","Techniques for making fungal activity visible","Management practices that favour fungal communities","Why trees are increasingly valued as infrastructure","Uncertainties in calculating financial benefits","The importance of equal access to healthy canopies","The visible tasks of tree maintenance"]'::jsonb, 3)
on conflict (slug) do update set
  title = excluded.title, body = excluded.body, topic = excluded.topic,
  headings = excluded.headings, difficulty = excluded.difficulty;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 1, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph B from the list of headings.',
              null, 'Two broad types are especially relevant to urban forestry.', 'Paragraph B explains the two main kinds of mycorrhizal relationship found in urban trees.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["The basic forms of a root-fungus partnership"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 2, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph C from the list of headings.',
              null, 'Urban conditions can weaken these alliances.', 'Paragraph C describes compaction, salts, metals, excavation and heat as factors that harm root-fungus relationships.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Urban stresses that damage underground alliances"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 3, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph D from the list of headings.',
              null, 'Newer studies combine DNA sequencing with measurements of soil chemistry, allowing scientists to identify fungi from tiny fragments in the soil.', 'Paragraph D focuses on research methods used to study fungi that are normally hidden underground.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Techniques for making fungal activity visible"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 4, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph E from the list of headings.',
              null, 'The most persuasive recommendations are not to add fungi indiscriminately, but to improve the habitat in which useful fungi already live.', 'Paragraph E discusses practical ways to protect or encourage beneficial fungi in urban soils.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Management practices that favour fungal communities"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 5, 'sentence_completion'::public.question_kind, 'Complete the sentence below. Write NO MORE THAN TWO WORDS from the passage. In paved streets, tree roots often occupy __________ surrounded by compacted subsoil, concrete and buried pipes.',
              null, 'In paved streets, tree roots often occupy narrow pits surrounded by compacted subsoil, concrete and buried pipes.', 'The missing words are taken directly from the sentence in Paragraph C.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["narrow pits"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 6, 'sentence_completion'::public.question_kind, 'Complete the sentence below. Write NO MORE THAN TWO WORDS from the passage. In ectomycorrhizal associations, fungal tissue forms a sheath around __________.',
              null, 'In ectomycorrhizal associations, fungal tissue forms a sheath around young roots and extends as threads into the surrounding soil.', 'The passage states that the sheath forms around young roots.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["young roots"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 7, 'sentence_completion'::public.question_kind, 'Complete the sentence below. Write NO MORE THAN TWO WORDS from the passage. The Melbourne survey found fungal species richness was lowest where soil had high __________.',
              null, 'A survey published in 2021 of street trees in Melbourne found that fungal species richness was lowest where soil had high bulk density and low organic matter.', 'The exact phrase describing the soil condition is “bulk density”.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["bulk density"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 8, 'sentence_completion'::public.question_kind, 'Complete the sentence below. Write NO MORE THAN TWO WORDS from the passage. Municipal crews can protect existing networks by leaving __________ under tree crowns.',
              null, 'Municipal crews can also protect existing networks by leaving leaf litter under tree crowns, limiting fungicide use and designing continuous soil trenches beneath pavements.', 'The passage identifies leaf litter as something crews can leave under tree crowns.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["leaf litter"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 9, 'true_false_not_given'::public.question_kind, 'Do the following statement agree with the information in the passage? Mature street trees can affect municipal budgets in indirect ways.',
              null, 'The services provided by mature street trees influence municipal budgets indirectly, because cooler pavements last longer, shaded buildings require less energy, and healthier neighbourhoods can reduce public health costs.', 'The statement matches the passage exactly: mature trees influence municipal budgets indirectly.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["TRUE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 10, 'true_false_not_given'::public.question_kind, 'Do the following statement agree with the information in the passage? Arbuscular mycorrhizal fungi can be recognised by conspicuous mushrooms at the soil surface.',
              null, 'Arbuscular mycorrhizal fungi enter root cells and are common in maples, planes and many tropical street trees; they do not produce conspicuous mushrooms at the soil surface.', 'The passage says these fungi do not produce conspicuous mushrooms, so the statement is false.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["FALSE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 11, 'true_false_not_given'::public.question_kind, 'Do the following statement agree with the information in the passage? The Melbourne survey was carried out entirely during summer.',
              null, 'A survey published in 2021 of street trees in Melbourne found that fungal species richness was lowest where soil had high bulk density and low organic matter.', 'The passage gives the publication year and findings of the survey, but it does not state the season in which the survey was conducted.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["NOT GIVEN"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 12, 'multiple_choice'::public.question_kind, 'According to the passage, why should commercial fungal inoculants be used cautiously?',
              '["They usually prevent seedlings from growing in nursery soils.","They may increase the temperature of soil beneath asphalt.","An introduced strain may fail to establish or may compete with fungi already adapted to the site.","They make it impossible to measure soil chemistry accurately."]'::jsonb, 'An introduced strain may fail to establish or may compete with fungi already adapted to the site.', 'This sentence gives the passage’s reason for caution about introduced fungal strains.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["An introduced strain may fail to establish or may compete with fungi already adapted to the site."]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'fungi-beneath-city-trees'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 13, 'multiple_choice'::public.question_kind, 'Why are the economic returns of mycorrhizal management difficult to calculate?',
              '["Because fungal contributions are indirect and interact with irrigation, pruning and the genetics of the tree.","Because most cities refuse to record the cost of watering street trees.","Because DNA sequencing cannot identify fungi from soil fragments.","Because mature canopies have no measurable effect on public health costs."]'::jsonb, 'The economic returns of mycorrhizal management are difficult to calculate, in part because fungal contributions are indirect and interact with irrigation, pruning and the genetics of the tree.', 'The correct option closely follows the explanation in Paragraph F.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Because fungal contributions are indirect and interact with irrigation, pruning and the genetics of the tree."]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

-- Mapping Drowned Prehistoric Landscapes
insert into public.passages (slug, title, body, topic, headings, difficulty)
values ('mapping-drowned-prehistoric-landscapes', 'Mapping Drowned Prehistoric Landscapes', 'A
For much of human history, coastlines were not fixed borders but moving zones of opportunity and risk. During the last glacial maximum, sea levels were more than 100 metres lower than today, exposing broad continental shelves around many coasts. These shelves contained rivers, lakes, forests and grasslands that could support hunting, gathering and later forms of settlement. Doggerland, the lowland that once linked Britain to continental Europe, is the best-known example in the North Sea. Its disappearance between about 12,000 and 7,000 years ago did not merely remove empty ground; it transformed migration routes, food resources and social contacts. Because many early coastal sites now lie beneath water, archaeologists argue that any account of prehistory based only on dry land is necessarily incomplete.

B
The first clues to many submerged landscapes came not from archaeologists but from industry. In the North Sea, petroleum companies collected thousands of kilometres of seismic data to locate oil and gas deposits below the seabed. Archaeologists realised that these records, although designed for engineering, could be reprocessed to reveal ancient river channels, lakes and coastlines. Computer modelling then allowed researchers to join scattered lines of evidence into three-dimensional maps of lost terrain. The method is not the same as excavation: it shows landforms rather than houses or tools. Nevertheless, mapping the shape of a former valley can help predict where people were likely to camp, fish or cross between regions.

C
Underwater preservation is both promising and frustrating. In such anoxic layers, organic materials break down much more slowly than they would on an exposed beach. Waterlogged sediments can preserve wood, bone, plant fibres and even footprints that would normally vanish within years. The same sediments often hide artefacts beneath metres of sand, silt or peat, where they are hard to distinguish from natural objects. Underwater deposits therefore create a paradox, because the conditions that protect delicate evidence can also make it difficult to find. By taking sediment cores, researchers can identify pollen, charcoal, microscopic shells and fragments of ancient DNA that indicate whether a place was forest, marsh or open water. These samples rarely provide dramatic museum pieces, but they can reconstruct the environments in which people made decisions.

D
Rising seas changed prehistoric lives gradually, unevenly and sometimes violently. The flooding of Doggerland was not a single catastrophic event, although sudden disasters may have accelerated local abandonment. Models suggest that communities repeatedly shifted camps, followed retreating shorelines and adapted to changing fish and shellfish habitats. The Storegga Slide, a submarine landslide off Norway about 8,200 years ago, generated a tsunami that may have devastated some remaining coastal groups, but the broader loss of land had begun long before. This long process matters because it shows that adaptation was not simply a matter of moving uphill. People also had to renegotiate territories, exchange networks and seasonal routines as familiar landmarks disappeared.

E
The practical difficulties are considerable: survey vessels are expensive, weather windows are narrow, and divers or remotely operated vehicles can examine only small areas at a time. These logistical constraints are accompanied by ethical questions, because excavation may disturb places that served as camps, ritual sites or burial grounds. Legal protection is also uneven, since national heritage laws were often written with shipwrecks or monuments on land in mind. In response, many researchers now favour minimally invasive approaches, such as acoustic survey, targeted coring and detailed recording before any object is removed. The aim is to treat submerged prehistoric sites not as isolated curiosities but as fragile archives whose context is as important as any artefact.

F
Interest in drowned landscapes is increasing as modern societies build more infrastructure offshore. In some regions, the growth of offshore wind farms has made archaeological assessment a routine part of marine planning. Developers, heritage agencies and scientists may collaborate to identify areas where cables, turbines or dredging could damage ancient deposits. Museum displays and digital reconstructions have also given these drowned landscapes an unusual public appeal. Yet their importance is not only educational. It reminds policymakers that coasts have always been dynamic places, while also showing that the speed and social consequences of change depend on technology, population and political choices. Studying submerged prehistory therefore links remote human experience with contemporary debates about sea-level rise.', 'Submerged prehistoric archaeology', '["A vanished plain at the edge of modern Europe","Industrial data turned into archaeological maps","Why water can both protect and obscure evidence","How rising seas changed human mobility","The logistical and ethical limits of investigation","From ancient shorelines to present-day policy","New methods for reconstructing lost environments","The public appeal of drowned worlds"]'::jsonb, 4)
on conflict (slug) do update set
  title = excluded.title, body = excluded.body, topic = excluded.topic,
  headings = excluded.headings, difficulty = excluded.difficulty;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 1, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph A from the list of headings.',
              null, 'Doggerland, the lowland that once linked Britain to continental Europe, is the best-known example in the North Sea.', 'Paragraph A introduces Doggerland as a now-submerged lowland that once connected Britain with Europe.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["A vanished plain at the edge of modern Europe"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 2, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph B from the list of headings.',
              null, 'Archaeologists realised that these records, although designed for engineering, could be reprocessed to reveal ancient river channels, lakes and coastlines.', 'Paragraph B explains how seismic records gathered for industry were reused to map prehistoric landscapes.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Industrial data turned into archaeological maps"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 3, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph C from the list of headings.',
              null, 'Underwater deposits therefore create a paradox, because the conditions that protect delicate evidence can also make it difficult to find.', 'Paragraph C focuses on the double effect of underwater conditions: preservation and concealment.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Why water can both protect and obscure evidence"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 4, 'matching_headings'::public.question_kind, 'Choose the correct heading for Paragraph E from the list of headings.',
              null, 'These logistical constraints are accompanied by ethical questions, because excavation may disturb places that served as camps, ritual sites or burial grounds.', 'Paragraph E discusses practical barriers as well as ethical concerns in investigating submerged sites.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["The logistical and ethical limits of investigation"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 5, 'true_false_not_given'::public.question_kind, 'During the last glacial maximum, lower sea levels exposed large areas of continental shelf.',
              null, 'During the last glacial maximum, sea levels were more than 100 metres lower than today, exposing broad continental shelves around many coasts.', 'The statement agrees with the passage, which says lower sea levels exposed broad shelves.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["TRUE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 6, 'true_false_not_given'::public.question_kind, 'All submerged prehistoric sites are destroyed quickly by water.',
              null, 'Waterlogged sediments can preserve wood, bone, plant fibres and even footprints that would normally vanish within years.', 'The passage states that waterlogged sediments can preserve evidence, so it contradicts the claim that all sites are destroyed quickly.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["FALSE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 7, 'true_false_not_given'::public.question_kind, 'Surveys of submerged landscapes are more expensive than archaeological excavations on land.',
              null, 'The practical difficulties are considerable: survey vessels are expensive, weather windows are narrow, and divers or remotely operated vehicles can examine only small areas at a time.', 'The passage says marine surveys are expensive, but it does not compare their cost with land excavations.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["NOT GIVEN"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 8, 'true_false_not_given'::public.question_kind, 'The Storegga tsunami was the only cause of Doggerland''s flooding.',
              null, 'The flooding of Doggerland was not a single catastrophic event, although sudden disasters may have accelerated local abandonment.', 'The passage says the flooding was not a single event, so the tsunami cannot be described as the only cause.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["FALSE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 9, 'multiple_choice'::public.question_kind, 'According to the passage, why were oil and gas seismic records useful to archaeologists?',
              '["They could be reprocessed to reveal ancient river channels, lakes and coastlines.","They contained photographs of prehistoric houses and tools.","They showed the exact locations of all burial grounds.","They measured the temperature of ancient seawater directly."]'::jsonb, 'Archaeologists realised that these records, although designed for engineering, could be reprocessed to reveal ancient river channels, lakes and coastlines.', 'The passage says seismic records made for engineering could be reused to identify ancient landscape features.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["They could be reprocessed to reveal ancient river channels, lakes and coastlines."]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 10, 'multiple_choice'::public.question_kind, 'What does the passage say sediment cores can help researchers identify?',
              '["Pollen, charcoal, microscopic shells and fragments of ancient DNA.","The names of prehistoric communities and their leaders.","The precise dates of every movement of the shoreline.","The original colours of wooden buildings above the water."]'::jsonb, 'By taking sediment cores, researchers can identify pollen, charcoal, microscopic shells and fragments of ancient DNA that indicate whether a place was forest, marsh or open water.', 'The listed materials are explicitly named as things sediment cores can identify.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Pollen, charcoal, microscopic shells and fragments of ancient DNA."]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 11, 'sentence_completion'::public.question_kind, 'Complete the sentence. Write NO MORE THAN TWO WORDS from the passage. In anoxic layers, ______ break down much more slowly than on an exposed beach.',
              null, 'In such anoxic layers, organic materials break down much more slowly than they would on an exposed beach.', 'The missing words are taken directly from the sentence in Paragraph C.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["organic materials"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 12, 'sentence_completion'::public.question_kind, 'Complete the sentence. Write NO MORE THAN TWO WORDS from the passage. Offshore wind farms have made archaeological assessment a routine part of ______.',
              null, 'In some regions, the growth of offshore wind farms has made archaeological assessment a routine part of marine planning.', 'The passage states that archaeological assessment has become a routine part of marine planning.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["marine planning"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'mapping-drowned-prehistoric-landscapes'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 13, 'yes_no_not_given'::public.question_kind, 'Does the writer agree that submerged prehistory is relevant to present-day decisions about coastal change?',
              null, 'It reminds policymakers that coasts have always been dynamic places, while also showing that the speed and social consequences of change depend on technology, population and political choices.', 'The writer connects submerged prehistory with policymakers and contemporary debates about sea-level rise, so the answer is YES.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["YES"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

-- The Invention of Clock Time
insert into public.passages (slug, title, body, topic, headings, difficulty)
values ('the-invention-of-clock-time', 'The Invention of Clock Time', 'A
For most of recorded history, time was a local matter. A town set its clocks by the sun: noon was the moment the sun stood highest over that particular place, and a settlement a hundred miles to the east reached that moment several minutes earlier. The discrepancy troubled almost nobody. A traveller moving by horse or on foot took days to cover a distance over which the difference amounted to a few minutes, and no institution required the two towns to agree.

B
The railway destroyed this arrangement. A train could cross in hours a distance that had previously taken days, and it ran to a printed timetable that assumed a single shared reckoning of the hour. When each station along a line kept its own solar time, a timetable became a document that was accurate nowhere. Worse, two trains sharing a single track and relying on scheduled passing points could be separated by a margin no greater than the disagreement between their station clocks.

C
Britain, with the densest early network, moved first. The Great Western Railway instructed its stations to keep London time from 1840, and other companies followed within a decade. The practice acquired a name of its own: railway time. Adoption beyond the stations was uneven and sometimes resented, since a town asked to abandon its own noon was being asked to accept that a distant capital defined its day. Some public clocks were fitted with two minute hands for a period, one showing local time and one showing London time. By 1855 the great majority of British public clocks had nevertheless been set to Greenwich Mean Time, though the change did not become a matter of law until the Statutes (Definition of Time) Act of 1880.

D
The problem was more severe in North America, where the continent spanned a far greater range of longitude and the railways were operated by many competing companies. Each railroad tended to keep the time of its own headquarters city, so a single station serving several lines might display several clocks, each correct for a different company. The Canadian engineer Sandford Fleming became a prominent advocate for a systematic solution, proposing that the world be divided into standard zones of one hour each. The North American railroads acted before any government did: on 18 November 1883 they adopted a scheme of standard time zones, and in the cities affected the clocks were reset at midday, producing what contemporaries called the day of two noons.

E
International agreement followed the next year. The International Meridian Conference, held in Washington in October 1884, resolved that the meridian passing through the observatory at Greenwich should serve as the world''s prime meridian, from which longitude and a universal day would be reckoned. The choice was practical rather than symbolic: a substantial majority of the world''s shipping already used charts based on Greenwich, and no rival meridian could claim comparable use. The conference did not, however, compel any country to adopt standard time internally, and national adoption continued piecemeal for decades.

F
What had changed was less the measurement of time than its authority. Before the railways, the sun over a town was the final arbiter of the hour, and a clock that disagreed with it was simply wrong. Afterwards the authority lay with a signal transmitted from elsewhere, and a clock was correct precisely insofar as it agreed with that signal, whatever the sun appeared to say. The modern experience of time as something received rather than observed begins here.', 'history of technology', '["Why local solar time went unquestioned","The timetable problem the railways created","Britain adopts a single railway time","Competing company clocks in North America","Reaching international agreement on a prime meridian","A change in where the authority over time resided","Legal recognition lagging behind common practice"]'::jsonb, 2)
on conflict (slug) do update set
  title = excluded.title, body = excluded.body, topic = excluded.topic,
  headings = excluded.headings, difficulty = excluded.difficulty;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 1, 'true_false_not_given'::public.question_kind, 'Before the railways, differences in time between nearby towns caused serious practical problems.',
              null, 'The discrepancy troubled almost nobody.', 'The passage states the discrepancy troubled almost nobody, which contradicts the claim.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["FALSE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 2, 'true_false_not_given'::public.question_kind, 'Railway timetables assumed that all stations used the same reckoning of the hour.',
              null, 'and it ran to a printed timetable that assumed a single shared reckoning of the hour.', 'Stated directly in paragraph B.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["TRUE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 3, 'true_false_not_given'::public.question_kind, 'More people died in railway collisions caused by clock discrepancies than by any other cause.',
              null, 'Worse, two trains sharing a single track and relying on scheduled passing points could be separated by a margin no greater than the disagreement between their station clocks.', 'The passage raises the safety risk but never compares causes of death, or gives any figures. This is not given.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["NOT GIVEN"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 4, 'true_false_not_given'::public.question_kind, 'Some British towns resisted the adoption of London time.',
              null, 'Adoption beyond the stations was uneven and sometimes resented, since a town asked to abandon its own noon was being asked to accept that a distant capital defined its day.', 'Resentment and uneven adoption are stated in paragraph C.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["TRUE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 5, 'true_false_not_given'::public.question_kind, 'Greenwich Mean Time became legally binding in Britain at the same time as most public clocks adopted it.',
              null, 'By 1855 the great majority of British public clocks had nevertheless been set to Greenwich Mean Time, though the change did not become a matter of law until the Statutes (Definition of Time) Act of 1880.', 'The clocks changed by 1855; the law followed in 1880. The two were not simultaneous.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["FALSE"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 6, 'multiple_choice'::public.question_kind, 'According to the passage, why was the timekeeping problem worse in North America than in Britain?',
              '["The continent covered a greater range of longitude and had many competing railway companies","North American trains travelled considerably faster","There were no observatories capable of determining accurate time","American passengers were less willing to accept printed timetables"]'::jsonb, 'The problem was more severe in North America, where the continent spanned a far greater range of longitude and the railways were operated by many competing companies.', 'Paragraph D names exactly these two reasons.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["The continent covered a greater range of longitude and had many competing railway companies"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 7, 'multiple_choice'::public.question_kind, 'The phrase ''the day of two noons'' refers to',
              '["the resetting of clocks at midday when standard time zones were adopted","a proposal by Sandford Fleming that was ultimately rejected","the two minute hands fitted to some British public clocks","the decision of the International Meridian Conference"]'::jsonb, 'on 18 November 1883 they adopted a scheme of standard time zones, and in the cities affected the clocks were reset at midday, producing what contemporaries called the day of two noons.', 'Stated directly in paragraph D.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["the resetting of clocks at midday when standard time zones were adopted"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 8, 'multiple_choice'::public.question_kind, 'Why was Greenwich chosen as the prime meridian?',
              '["Most of the world''s shipping already used charts based on it","Britain had the densest railway network in the world","It was the only observatory represented at the conference","Sandford Fleming had recommended it specifically"]'::jsonb, 'The choice was practical rather than symbolic: a substantial majority of the world''s shipping already used charts based on Greenwich, and no rival meridian could claim comparable use.', 'Paragraph E gives the practical reason explicitly.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Most of the world''s shipping already used charts based on it"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 9, 'sentence_completion'::public.question_kind, 'The practice of railway companies keeping a single shared time acquired the name ................ . (TWO WORDS)',
              null, 'The practice acquired a name of its own: railway time.', 'Lifted verbatim from paragraph C.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["railway time"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 10, 'sentence_completion'::public.question_kind, 'The Great Western Railway told its stations to keep London time from the year ................ . (ONE NUMBER)',
              null, 'The Great Western Railway instructed its stations to keep London time from 1840, and other companies followed within a decade.', 'Stated in paragraph C.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["1840"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 11, 'sentence_completion'::public.question_kind, 'During the transition, some British public clocks were fitted with two ................ . (TWO WORDS)',
              null, 'Some public clocks were fitted with two minute hands for a period, one showing local time and one showing London time.', 'Lifted verbatim from paragraph C.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["minute hands"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 12, 'matching_headings'::public.question_kind, 'Choose the most suitable heading for paragraph F.',
              null, 'What had changed was less the measurement of time than its authority.', 'Paragraph F is explicitly about authority shifting from the sun to a transmitted signal.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["A change in where the authority over time resided"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

with p as (select id from public.passages where slug = 'the-invention-of-clock-time'),
     q as (
       insert into public.questions (passage_id, idx, kind, prompt, options, evidence, explanation)
       select p.id, 13, 'matching_headings'::public.question_kind, 'Choose the most suitable heading for paragraph E.',
              null, 'International agreement followed the next year.', 'Paragraph E covers the 1884 Washington conference and the choice of Greenwich.'
       from p
       on conflict (passage_id, idx) do update set
         kind = excluded.kind, prompt = excluded.prompt, options = excluded.options,
         evidence = excluded.evidence, explanation = excluded.explanation
       returning id
     )
insert into public.question_answers (question_id, answer)
select q.id, '["Reaching international agreement on a prime meridian"]'::jsonb from q
on conflict (question_id) do update set answer = excluded.answer;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task2-remote-work', 2, 'academic'::public.test_format, 'Some people believe that allowing employees to work from home permanently benefits both companies and workers. Others argue that it weakens teams and harms younger employees in particular.

Discuss both these views and give your own opinion.

Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.', null)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task2-museums-free', 2, 'academic'::public.test_format, 'In some countries, entry to national museums and galleries is free of charge. In others, visitors are expected to pay.

Do the advantages of free entry outweigh the disadvantages?

Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.', null)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task2-university-subjects', 2, 'academic'::public.test_format, 'Some people think universities should only offer subjects that are useful in the future job market, such as those related to science and technology. Others believe that subjects like history, philosophy and literature remain essential.

Discuss both views and give your own opinion.

Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.', null)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-smartphone-ownership', 1, 'academic'::public.test_format, 'The line graph below shows the percentage of adults who owned a smartphone in three countries between 2008 and 2023.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"line","title":"Adults owning a smartphone, 2008-2023","unit":"% of adults","xLabel":"Year","series":[{"name":"South Korea","points":[[2008,2],[2011,24],[2014,74],[2017,89],[2020,93],[2023,95]]},{"name":"United States","points":[[2008,1],[2011,18],[2014,58],[2017,77],[2020,85],[2023,90]]},{"name":"Nigeria","points":[[2008,0],[2011,3],[2014,9],[2017,21],[2020,32],[2023,45]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-household-spending', 1, 'academic'::public.test_format, 'The bar chart below shows the average monthly household spending on four categories in two countries in 2022.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"bar","title":"Average monthly household spending, 2022","unit":"USD","xLabel":"Category","series":[{"name":"Country A","points":[["Housing",1200],["Food",500],["Transport",300],["Leisure",250]]},{"name":"Country B","points":[["Housing",650],["Food",420],["Transport",180],["Leisure",150]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-renewable-energy', 1, 'academic'::public.test_format, 'The graph below shows the share of electricity generated from renewable sources in three countries between 1995 and 2020.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"line","title":"Electricity from renewable sources, 1995-2020","unit":"% of total generation","xLabel":"Year","series":[{"name":"Denmark","points":[[1995,6],[2000,16],[2005,24],[2010,33],[2015,52],[2020,67]]},{"name":"Germany","points":[[1995,4],[2000,7],[2005,11],[2010,17],[2015,30],[2020,45]]},{"name":"Poland","points":[[1995,2],[2000,2],[2005,3],[2010,7],[2015,13],[2020,17]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-commute-mode', 1, 'academic'::public.test_format, 'The bar chart below shows how workers travelled to their workplace in one city in 2000 and 2020.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"bar","title":"Method of travel to work, 2000 vs 2020","unit":"% of workers","xLabel":"Mode","series":[{"name":"2000","points":[["Car",58],["Public transport",24],["Cycling",6],["Walking",12]]},{"name":"2020","points":[["Car",41],["Public transport",31],["Cycling",18],["Walking",10]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-international-students', 1, 'academic'::public.test_format, 'The line graph below shows the number of students from three countries who enrolled in universities abroad between 2005 and 2020.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"line","title":"Students enrolled in universities abroad, 2005-2020","unit":"thousands","xLabel":"Year","series":[{"name":"China","points":[[2005,118],[2010,265],[2015,460],[2020,590]]},{"name":"India","points":[[2005,60],[2010,145],[2015,220],[2020,310]]},{"name":"South Korea","points":[[2005,75],[2010,105],[2015,100],[2020,85]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-working-hours', 1, 'academic'::public.test_format, 'The bar chart below shows the average number of hours worked per week in four industries in two countries in 2021.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"bar","title":"Average weekly working hours by industry, 2021","unit":"hours","xLabel":"Industry","series":[{"name":"Country A","points":[["Agriculture",46],["Manufacturing",42],["Retail",38],["Finance",40]]},{"name":"Country B","points":[["Agriculture",39],["Manufacturing",37],["Retail",33],["Finance",36]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

insert into public.writing_prompts (slug, task, format, prompt_text, chart_data)
values ('task1-academic-co2-emissions', 1, 'academic'::public.test_format, 'The graph below shows carbon dioxide emissions per person in three countries between 1990 and 2020.

Summarise the information by selecting and reporting the main features, and make comparisons where relevant.

Write at least 150 words.', '{"kind":"line","title":"CO2 emissions per capita, 1990-2020","unit":"tonnes per person","xLabel":"Year","series":[{"name":"United States","points":[[1990,19.3],[2000,20.2],[2010,17.6],[2020,13.7]]},{"name":"United Kingdom","points":[[1990,9.9],[2000,9.2],[2010,7.7],[2020,4.8]]},{"name":"Brazil","points":[[1990,1.4],[2000,1.8],[2010,2.1],[2020,2]]}]}'::jsonb)
on conflict (slug) do update set
  task = excluded.task, format = excluded.format, prompt_text = excluded.prompt_text,
  chart_data = excluded.chart_data;

commit;
