-- Generated by scripts/generate-speaking-content.mts. Edit the JSON in
-- content/speaking/, then regenerate; do not hand-edit this file.

begin;

-- Speaking — a busy day you handled well
insert into public.speaking_tests (slug, title, topic, difficulty)
values ('a-busy-day-you-handled-well', 'Speaking — a busy day you handled well', 'Managing time and responsibilities', 3)
on conflict (slug) do update set
  title = excluded.title, topic = excluded.topic, difficulty = excluded.difficulty;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 1, 1, 'What part of your daily routine is usually the busiest?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-1.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 2, 1, 'How do you usually organize the things you need to do each day?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-2.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 3, 1, 'What do you like to do when you have a completely free day?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-3.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 4, 2, 'Describe a particularly busy day that you managed well. You should say:',
       '["when the day was","what you had to do","how you organized your time","and explain how you felt at the end of the day."]'::jsonb, 60, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-4.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 5, 3, 'Why do many people feel that their lives are becoming busier?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-5.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 6, 3, 'What are the main consequences of having too many responsibilities?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-6.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 7, 3, 'How should employers help workers manage heavy workloads?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-7.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 8, 3, 'In what ways has technology made time management easier or more difficult?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-8.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 9, 3, 'How do you think attitudes toward work-life balance will change in the future?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-busy-day-you-handled-well-9.mp3'
from public.speaking_tests st where st.slug = 'a-busy-day-you-handled-well'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

-- Speaking — a helpful conversation you remember
insert into public.speaking_tests (slug, title, topic, difficulty)
values ('a-helpful-conversation-you-remember', 'Speaking — a helpful conversation you remember', 'Advice, communication and exchanging ideas', 3)
on conflict (slug) do update set
  title = excluded.title, topic = excluded.topic, difficulty = excluded.difficulty;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 1, 1, 'Who do you usually talk to when you need advice?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-1.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 2, 1, 'Do you prefer having long conversations or short ones?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-2.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 3, 1, 'What topics do you most enjoy discussing with your friends?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-3.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 4, 2, 'Describe a conversation that was particularly helpful to you. You should say:',
       '["who you had the conversation with","when and where it happened","what you talked about","and explain why the conversation was helpful."]'::jsonb, 60, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-4.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 5, 3, 'What makes someone good at giving advice?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-5.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 6, 3, 'Why are people sometimes unwilling to follow advice even when it is sensible?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-6.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 7, 3, 'How has online communication changed the way people discuss personal problems?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-7.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 8, 3, 'What differences are there between getting advice from friends and getting advice from professionals?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-8.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 9, 3, 'How important will face-to-face conversation remain as artificial intelligence and digital communication become more common?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-helpful-conversation-you-remember-9.mp3'
from public.speaking_tests st where st.slug = 'a-helpful-conversation-you-remember'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

-- Speaking — a skill you learned from someone
insert into public.speaking_tests (slug, title, topic, difficulty)
values ('a-skill-you-learned-from-someone', 'Speaking — a skill you learned from someone', 'Learning useful skills from other people', 3)
on conflict (slug) do update set
  title = excluded.title, topic = excluded.topic, difficulty = excluded.difficulty;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 1, 1, 'What kind of things do you enjoy learning in your free time?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-1.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 2, 1, 'How do you usually learn a new skill?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-2.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 3, 1, 'Is there a skill you would like to improve at the moment?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-3.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 4, 1, 'Did you enjoy learning new things when you were a child?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-4.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 5, 2, 'Describe a useful skill that someone taught you. You should say:',
       '["what the skill was","who taught it to you and when","how you learned to do it","and explain why this skill has been useful to you."]'::jsonb, 60, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-5.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 6, 3, 'What kinds of practical skills are most important for young people to learn?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-6.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 7, 3, 'How does learning directly from another person differ from learning through videos or online courses?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-7.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 8, 3, 'Why are some people more willing than others to share their knowledge and skills?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-8.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 9, 3, 'How might technology change the way people learn practical skills in the future?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/a-skill-you-learned-from-someone-9.mp3'
from public.speaking_tests st where st.slug = 'a-skill-you-learned-from-someone'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

-- Speaking — an object you have kept for years
insert into public.speaking_tests (slug, title, topic, difficulty)
values ('an-object-you-have-kept-for-years', 'Speaking — an object you have kept for years', 'Personal possessions and their emotional value', 3)
on conflict (slug) do update set
  title = excluded.title, topic = excluded.topic, difficulty = excluded.difficulty;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 1, 1, 'What kinds of things do you usually keep in your room?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-1.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 2, 1, 'Do you prefer to keep your belongings well organized?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-2.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 3, 1, 'Are there any things you find difficult to throw away?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-3.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 4, 2, 'Describe an object that you have kept for a long time. You should say:',
       '["what the object is","when and how you got it","where you usually keep it","and explain why you have kept it for so long."]'::jsonb, 60, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-4.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 5, 3, 'Why do people become emotionally attached to ordinary objects?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-5.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 6, 3, 'How have people''s attitudes toward keeping possessions changed as consumer culture has grown?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-6.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 7, 3, 'What factors make an object valuable even when it is worth very little money?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-7.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 8, 3, 'How does passing possessions from one generation to another benefit families?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-8.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 9, 3, 'What effect might digital photographs and records have on the kinds of physical objects people preserve in the future?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-object-you-have-kept-for-years-9.mp3'
from public.speaking_tests st where st.slug = 'an-object-you-have-kept-for-years'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

-- Speaking — an outdoor activity you enjoyed
insert into public.speaking_tests (slug, title, topic, difficulty)
values ('an-outdoor-activity-you-enjoyed', 'Speaking — an outdoor activity you enjoyed', 'Outdoor recreation and access to nature', 3)
on conflict (slug) do update set
  title = excluded.title, topic = excluded.topic, difficulty = excluded.difficulty;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 1, 1, 'How much time do you usually spend outdoors?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-1.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 2, 1, 'What outdoor activities are popular where you live?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-2.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 3, 1, 'What kind of weather do you prefer when you are outside?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-3.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 4, 1, 'Did you spend much time outdoors when you were younger?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-4.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 5, 2, 'Describe an outdoor activity that you enjoyed doing. You should say:',
       '["what the activity was","where and when you did it","who you did it with","and explain what made the experience enjoyable."]'::jsonb, 60, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-5.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 6, 3, 'Why do some people prefer outdoor recreation while others prefer indoor activities?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-6.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 7, 3, 'What benefits can cities gain from providing more parks and outdoor recreational spaces?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-7.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 8, 3, 'What prevents people living in large cities from spending more time in nature?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-8.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 9, 3, 'How should governments balance the protection of natural areas with public access to them?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-9.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

insert into public.speaking_prompts (test_id, idx, part, text, cue_card_points, prep_seconds, audio_url)
select st.id, 10, 3, 'How might outdoor leisure activities change as cities become larger and more densely populated?',
       null, 0, 'https://pub-fbae5ca09eba4fd0820da2b390dd7ca0.r2.dev/speaking/an-outdoor-activity-you-enjoyed-10.mp3'
from public.speaking_tests st where st.slug = 'an-outdoor-activity-you-enjoyed'
on conflict (test_id, idx) do update set
  part = excluded.part, text = excluded.text, cue_card_points = excluded.cue_card_points,
  prep_seconds = excluded.prep_seconds, audio_url = excluded.audio_url;

commit;
