import { task, timed } from './task.ts';
import type { ExamDefinition } from './types.ts';

/**
 * Duolingo English Test after the 1 July 2025 update removed Read Aloud and
 * Listen, Then Speak (19 question types). One adaptive sitting of about an
 * hour; grouped here by the individual subscore each type mainly feeds. The
 * integrated subscores (Literacy, Comprehension, Conversation, Production)
 * come from `measuredSkills` combinations, not from sections.
 *
 * ponytail: the adaptive part shares one clock, so most types are
 * section-timed; response windows are Duolingo's published guidance.
 */
export const DET = {
  key: 'det',
  name: 'Duolingo English Test',
  version: '2025-07-01',
  source: 'https://englishtest.duolingo.com/scores',
  variants: [],
  scoreScale: { label: 'Score', min: 10, max: 160, step: 5 },
  targetRange: { min: 60, max: 160, step: 10 },
  sections: [
    { key: 'reading', label: 'Reading', skills: ['reading'], minutes: null },
    {
      key: 'listening',
      label: 'Listening',
      skills: ['listening'],
      minutes: null,
    },
    { key: 'writing', label: 'Writing', skills: ['writing'], minutes: null },
    { key: 'speaking', label: 'Speaking', skills: ['speaking'], minutes: null },
  ],
  tasks: [
    task(
      'reading',
      'read_and_complete',
      'Read and Complete',
      'text',
      'fill_blank',
      'fill_blank',
      'gap_match',
      ['reading', 'writing'],
      timed(0, 180),
    ),
    task(
      'reading',
      'read_and_select',
      'Read and Select',
      'text',
      'multi_choice',
      'multi_choice',
      'multi_match',
      ['reading'],
      timed(0, 60),
    ),
    task(
      'reading',
      'fill_in_the_blanks',
      'Fill in the Blanks',
      'text',
      'fill_blank',
      'fill_blank',
      'gap_match',
      ['reading', 'writing'],
    ),
    task(
      'reading',
      'complete_the_sentences',
      'Complete the Sentences',
      'text',
      'single_choice',
      'choice_select',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'complete_the_passage',
      'Complete the Passage',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'highlight_the_answer',
      'Highlight the Answer',
      'text',
      'text',
      'text_input',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'identify_the_idea',
      'Identify the Idea',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'title_the_passage',
      'Title the Passage',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'listening',
      'listen_and_type',
      'Listen and Type',
      'audio',
      'text',
      'text_input',
      'dictation_match',
      ['listening', 'writing'],
      timed(0, 60),
    ),
    task(
      'listening',
      'listen_and_respond',
      'Listen and Respond',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening', 'speaking'],
    ),
    task(
      'listening',
      'listen_and_complete',
      'Listen and Complete',
      'audio',
      'fill_blank',
      'fill_blank',
      'gap_match',
      ['listening'],
    ),
    task(
      'listening',
      'summarize_the_conversation',
      'Summarize the Conversation',
      'audio',
      'text',
      'essay',
      'writing_model',
      ['listening', 'writing'],
      timed(0, 75),
    ),
    task(
      'writing',
      'write_about_the_photo',
      'Write About the Photo',
      'image',
      'text',
      'essay',
      'writing_model',
      ['writing'],
      timed(0, 60),
    ),
    task(
      'writing',
      'interactive_writing',
      'Interactive Writing',
      'text',
      'text',
      'essay',
      'writing_model',
      ['writing'],
      timed(0, 480),
    ),
    task(
      'writing',
      'writing_sample',
      'Writing Sample',
      'text',
      'text',
      'essay',
      'writing_model',
      ['writing'],
      timed(30, 300),
    ),
    task(
      'speaking',
      'speak_about_the_photo',
      'Speak About the Photo',
      'image',
      'audio',
      'recording',
      'speaking_model',
      ['speaking'],
      timed(20, 90),
    ),
    task(
      'speaking',
      'read_then_speak',
      'Read, Then Speak',
      'text',
      'audio',
      'recording',
      'speaking_model',
      ['reading', 'speaking'],
      timed(20, 90),
    ),
    task(
      'speaking',
      'interactive_speaking',
      'Interactive Speaking',
      'audio',
      'conversation',
      'conversation',
      'speaking_model',
      ['listening', 'speaking'],
      timed(0, 35),
    ),
    task(
      'speaking',
      'speaking_sample',
      'Speaking Sample',
      'text',
      'audio',
      'recording',
      'speaking_model',
      ['speaking'],
      timed(30, 180),
    ),
  ],
} as const satisfies ExamDefinition;
