import { mins, task, timed } from './task.ts';
import type { ExamDefinition } from './types.ts';

/**
 * IELTS, as Bandzen already runs it. Reading and Listening tasks are keyed
 * `<section>_<question kind>` so a question row resolves to its task without a
 * lookup table (see `ieltsQuestionTask`). Speaking caps match the recorder's.
 */
export const IELTS = {
  key: 'ielts',
  name: 'IELTS',
  version: '2026',
  source: 'https://ielts.org/take-a-test/test-types/ielts-academic-test',
  // The sitting Bandzen runs, gaps between sections included.
  duration: 'About 2 hr 45 min',
  variants: [
    { key: 'academic', label: 'Academic' },
    { key: 'general', label: 'General Training' },
  ],
  scoreScale: { label: 'Band', min: 0, max: 9, step: 0.5 },
  targetRange: { min: 5, max: 9, step: 0.5 },
  sections: [
    {
      key: 'listening',
      label: 'Listening',
      skills: ['listening'],
      minutes: mins(30),
    },
    {
      key: 'reading',
      label: 'Reading',
      skills: ['reading'],
      minutes: mins(60),
    },
    {
      key: 'writing',
      label: 'Writing',
      skills: ['writing'],
      minutes: mins(60),
    },
    {
      key: 'speaking',
      label: 'Speaking',
      skills: ['speaking'],
      minutes: mins(14),
    },
  ],
  tasks: [
    task(
      'listening',
      'listening_multiple_choice',
      'Multiple choice',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
    ),
    task(
      'listening',
      'listening_sentence_completion',
      'Sentence completion',
      'audio',
      'text',
      'text_input',
      'exact_match',
      ['listening'],
    ),
    task(
      'listening',
      'listening_matching',
      'Matching',
      'audio',
      'single_choice',
      'choice_select',
      'exact_match',
      ['listening'],
    ),
    task(
      'reading',
      'reading_true_false_not_given',
      'True / False / Not Given',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'reading_yes_no_not_given',
      'Yes / No / Not Given',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'reading_multiple_choice',
      'Multiple choice',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'reading_matching_headings',
      'Matching headings',
      'text',
      'single_choice',
      'choice_select',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'reading_sentence_completion',
      'Sentence completion',
      'text',
      'text',
      'text_input',
      'exact_match',
      ['reading'],
    ),
    task(
      'writing',
      'writing_task_1',
      'Writing Task 1',
      'mixed',
      'text',
      'essay',
      'writing_model',
      ['writing'],
    ),
    task(
      'writing',
      'writing_task_2',
      'Writing Task 2',
      'text',
      'text',
      'essay',
      'writing_model',
      ['writing'],
    ),
    task(
      'speaking',
      'speaking_part_1',
      'Speaking Part 1',
      'audio',
      'audio',
      'recording',
      'speaking_model',
      ['speaking'],
      timed(0, 45),
    ),
    task(
      'speaking',
      'speaking_part_2',
      'Speaking Part 2',
      'mixed',
      'audio',
      'recording',
      'speaking_model',
      ['speaking'],
      timed(60, 120),
    ),
    task(
      'speaking',
      'speaking_part_3',
      'Speaking Part 3',
      'audio',
      'audio',
      'recording',
      'speaking_model',
      ['speaking'],
      timed(0, 60),
    ),
  ],
} as const satisfies ExamDefinition;
