import { ONE_PLAY, SECTION_TIMED, task, timed, withWords } from './task.ts';
import type { ExamDefinition } from './types.ts';

/**
 * PTE Academic after the 7 August 2025 update, which added Summarize Group
 * Discussion and Respond to a Situation (22 scored task types). Section
 * minutes are the upper end of Pearson's published ranges.
 *
 * ponytail: per-task times are Pearson's published windows; the within-section
 * items (Reading, most of Listening) share the section clock. Calibrate against
 * the official practice test before building a timed PTE mock.
 */
export const PTE_ACADEMIC = {
  key: 'pte_academic',
  name: 'PTE Academic',
  version: '2025-08-07',
  source:
    'https://www.pearsonpte.com/articles/pte-changes-2025-everything-you-need-to-know/',
  variants: [],
  scoreScale: { label: 'Score', min: 10, max: 90, step: 1 },
  targetRange: { min: 30, max: 90, step: 5 },
  sections: [
    {
      key: 'speaking_writing',
      label: 'Speaking & Writing',
      skills: ['speaking', 'writing'],
      minutes: 67,
    },
    { key: 'reading', label: 'Reading', skills: ['reading'], minutes: 30 },
    {
      key: 'listening',
      label: 'Listening',
      skills: ['listening'],
      minutes: 43,
    },
  ],
  tasks: [
    task(
      'speaking_writing',
      'read_aloud',
      'Read Aloud',
      'text',
      'audio',
      'recording',
      'speaking_model',
      ['reading', 'speaking'],
      timed(35, 40),
    ),
    task(
      'speaking_writing',
      'repeat_sentence',
      'Repeat Sentence',
      'audio',
      'audio',
      'recording',
      'speaking_model',
      ['listening', 'speaking'],
      timed(0, 15),
      ONE_PLAY,
    ),
    task(
      'speaking_writing',
      'describe_image',
      'Describe Image',
      'image',
      'audio',
      'recording',
      'speaking_model',
      ['speaking'],
      timed(25, 40),
    ),
    task(
      'speaking_writing',
      'retell_lecture',
      'Re-tell Lecture',
      'mixed',
      'audio',
      'recording',
      'speaking_model',
      ['listening', 'speaking'],
      timed(10, 40),
      ONE_PLAY,
    ),
    task(
      'speaking_writing',
      'answer_short_question',
      'Answer Short Question',
      'audio',
      'audio',
      'recording',
      'speaking_model',
      ['listening', 'speaking'],
      timed(0, 10),
      ONE_PLAY,
    ),
    task(
      'speaking_writing',
      'summarize_group_discussion',
      'Summarize Group Discussion',
      'audio',
      'audio',
      'recording',
      'speaking_model',
      ['listening', 'speaking'],
      timed(10, 120),
      ONE_PLAY,
    ),
    task(
      'speaking_writing',
      'respond_to_a_situation',
      'Respond to a Situation',
      'mixed',
      'audio',
      'recording',
      'speaking_model',
      ['listening', 'speaking'],
      timed(10, 40),
      ONE_PLAY,
    ),
    withWords(
      task(
        'speaking_writing',
        'summarize_written_text',
        'Summarize Written Text',
        'text',
        'text',
        'essay',
        'writing_model',
        ['reading', 'writing'],
        timed(0, 600),
      ),
      5,
      75,
    ),
    withWords(
      task(
        'speaking_writing',
        'write_essay',
        'Write Essay',
        'text',
        'text',
        'essay',
        'writing_model',
        ['writing'],
        timed(0, 1200),
      ),
      200,
      300,
    ),
    task(
      'reading',
      'reading_writing_fill_in_the_blanks',
      'Reading & Writing: Fill in the Blanks',
      'text',
      'fill_blank',
      'fill_blank_select',
      'gap_match',
      ['reading', 'writing'],
    ),
    task(
      'reading',
      'reading_multiple_choice_multiple',
      'Multiple Choice, Multiple Answers',
      'text',
      'multi_choice',
      'multi_choice',
      'multi_match',
      ['reading'],
    ),
    task(
      'reading',
      'reorder_paragraphs',
      'Re-order Paragraphs',
      'text',
      'reorder',
      'reorder',
      'order_match',
      ['reading'],
    ),
    task(
      'reading',
      'reading_fill_in_the_blanks',
      'Reading: Fill in the Blanks',
      'text',
      'fill_blank',
      'fill_blank_drag',
      'gap_match',
      ['reading'],
    ),
    task(
      'reading',
      'reading_multiple_choice_single',
      'Multiple Choice, Single Answer',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    withWords(
      task(
        'listening',
        'summarize_spoken_text',
        'Summarize Spoken Text',
        'audio',
        'text',
        'essay',
        'writing_model',
        ['listening', 'writing'],
        timed(0, 600),
        ONE_PLAY,
      ),
      50,
      70,
    ),
    task(
      'listening',
      'listening_multiple_choice_multiple',
      'Multiple Choice, Multiple Answers',
      'audio',
      'multi_choice',
      'multi_choice',
      'multi_match',
      ['listening'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
    task(
      'listening',
      'listening_fill_in_the_blanks',
      'Fill in the Blanks',
      'mixed',
      'fill_blank',
      'fill_blank',
      'gap_match',
      ['listening', 'writing'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
    task(
      'listening',
      'highlight_correct_summary',
      'Highlight Correct Summary',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening', 'reading'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
    task(
      'listening',
      'listening_multiple_choice_single',
      'Multiple Choice, Single Answer',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
    task(
      'listening',
      'select_missing_word',
      'Select Missing Word',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
    task(
      'listening',
      'highlight_incorrect_words',
      'Highlight Incorrect Words',
      'mixed',
      'multi_choice',
      'multi_choice',
      'multi_match',
      ['listening', 'reading'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
    task(
      'listening',
      'write_from_dictation',
      'Write from Dictation',
      'audio',
      'text',
      'text_input',
      'dictation_match',
      ['listening', 'writing'],
      SECTION_TIMED,
      ONE_PLAY,
    ),
  ],
} as const satisfies ExamDefinition;
