import { task, timed } from './task.ts';
import type { ExamDefinition } from './types.ts';

/**
 * TOEFL iBT for tests from 21 January 2026: adaptive Reading and Listening,
 * section band scores of 1–6 in half steps, overall the mean of the four.
 * The 0–120 format before that date is a different version, not modelled.
 *
 * ponytail: adaptive sections have no fixed length, so their `minutes` is
 * null; response windows are ETS's published guidance. Calibrate against the
 * official TOEFL practice test before building a timed mock.
 */
export const TOEFL_IBT = {
  key: 'toefl_ibt',
  name: 'TOEFL iBT',
  version: '2026-01-21',
  source: 'https://www.ets.org/toefl/test-takers/ibt/about/content.html',
  variants: [],
  scoreScale: { label: 'Band', min: 1, max: 6, step: 0.5 },
  targetRange: { min: 3, max: 6, step: 0.5 },
  sections: [
    { key: 'reading', label: 'Reading', skills: ['reading'], minutes: null },
    {
      key: 'listening',
      label: 'Listening',
      skills: ['listening'],
      minutes: null,
    },
    { key: 'writing', label: 'Writing', skills: ['writing'], minutes: 23 },
    { key: 'speaking', label: 'Speaking', skills: ['speaking'], minutes: 8 },
  ],
  tasks: [
    task(
      'reading',
      'complete_the_words',
      'Complete the Words',
      'text',
      'fill_blank',
      'fill_blank',
      'gap_match',
      ['reading'],
    ),
    task(
      'reading',
      'read_in_daily_life',
      'Read in Daily Life',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'reading',
      'read_an_academic_passage',
      'Read an Academic Passage',
      'text',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['reading'],
    ),
    task(
      'listening',
      'listen_and_choose_a_response',
      'Listen and Choose a Response',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
    ),
    task(
      'listening',
      'listen_to_a_conversation',
      'Listen to a Conversation',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
    ),
    task(
      'listening',
      'listen_to_an_announcement',
      'Listen to an Announcement',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
    ),
    task(
      'listening',
      'listen_to_an_academic_talk',
      'Listen to an Academic Talk',
      'audio',
      'single_choice',
      'choice_cards',
      'exact_match',
      ['listening'],
    ),
    task(
      'writing',
      'build_a_sentence',
      'Build a Sentence',
      'text',
      'reorder',
      'sentence_builder',
      'order_match',
      ['writing'],
    ),
    task(
      'writing',
      'write_an_email',
      'Write an Email',
      'text',
      'text',
      'essay',
      'writing_model',
      ['writing'],
      timed(0, 420),
    ),
    task(
      'writing',
      'write_for_an_academic_discussion',
      'Write for an Academic Discussion',
      'text',
      'text',
      'essay',
      'writing_model',
      ['reading', 'writing'],
      timed(0, 600),
    ),
    task(
      'speaking',
      'listen_and_repeat',
      'Listen and Repeat',
      'audio',
      'audio',
      'recording',
      'speaking_model',
      ['listening', 'speaking'],
      timed(0, 15),
    ),
    task(
      'speaking',
      'take_an_interview',
      'Take an Interview',
      'audio',
      'conversation',
      'conversation',
      'speaking_model',
      ['listening', 'speaking'],
      timed(0, 45),
    ),
  ],
} as const satisfies ExamDefinition;
